[package]
name = "craft-show-entry-cards"
authors = ["Mike Croall"]
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
console_error_panic_hook = "0.1.7"
derive_typst_intoval = "0.8.0"
leptos = { version = "0.8.17", features = ["csr"] }
leptos-use = "0.19.0"
typst = "0.15.0"
typst-as-lib = "0.16.0"
typst-pdf = "0.15.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
