[package]
name = "craft-show-entry-cards"
author = "Mike Croall"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_typst_intoval = "0.5.0"
typst = "0.13.1"
typst-as-lib = "0.14.4"
typst-pdf = "0.13.1"
