name: Rust CI

on:
    push:
        paths:
            - "**.rs"
            - "**.toml"
            - "**.lock"
            - "**.html"
            - "**/typst/**"
            - "**rust-ci.yml"
    pull_request:
        paths:
            - "**.rs"
            - "**.toml"
            - "**.lock"
            - "**.html"
            - "**/typst/**"
            - "**rust-ci.yml"

env:
    CARGO_TERM_COLOR: always

jobs:
    build-test-lint-audit:
        name: Build, test, clippy, audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Use dependencies cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-
            - name: Build
              run: cargo build --verbose
            - name: Install cargo-nextest
              uses: taiki-e/install-action@nextest
            - name: Test
              run: cargo nextest run --verbose
            - name: Clippy
              run: cargo clippy --verbose -- -D warnings
            - name: Check fmt
              run: cargo fmt --all -- --check
            - name: Audit Rust Dependencies
              uses: actions-rust-lang/audit@v1

    publish-github-pages:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest

        needs: build-test-lint-audit
        if: github.ref_name == github.event.repository.default_branch

        permissions:
            id-token: write
            pages: write

        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust Stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Install trunk for WASM build
              uses: taiki-e/install-action@trunk

            - name: Build wasm page
              run: |
                  trunk build --release

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./dist"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
